### ISSUE TITLE
Feature request: Inline comments in rcp scripts

### ISSUE THREAD

**Issue by frans-bergman** [dSynMa/recipe#16]
It would be nice to be able to add inline comments to recipe script files. I could not find any mention of comments in the source code, nor in the papers. Is this feature available, and if so, what is the correct syntax?

**Comment by shaunazzopardi** [comment]
It's not available yet unfortunately, we plan to however. I will let you know when it is implemented

**Comment by shaunazzopardi** [comment]
Closing this, will be part of #27.
