### ISSUE TITLE
Errors when running 'npm install' in the 'frontend-react' directory

### ISSUE THREAD

**Issue by aaniculaesei** [dSynMa/recipe#38]
Hi, I get the following error when executing 'npm install' in the 'frontend-react' directory.

`Error: command failed
     at ChildProcess.<anonymous> (/usr/share/nodejs/@npmcli/promise-spawn/index.js:64:27)
     at ChildProcess.emit (events.js:314:20)
     at maybeClose (internal/child_process.js:1022:16)
     at Socket.<anonymous> (internal/child_process.js:444:11)
     at Socket.emit (events.js:314:20)
     at Pipe.<anonymous> (net.js:676:12)`

A complete log of the execution of 'npm install' is attached. Thank you for your help, Adina.

[2024-10-14T14_06_30_332Z-debug-0.log](https://github.com/user-attachments/files/17365675/2024-10-14T14_06_30_332Z-debug-0.log)

**Comment by lou1306** [comment]
This is due to the fact that we have a `.npmrc` file with this content:

```ini
node-options="--openssl-legacy-provider"
```

We added that because of some issues with how new versions of react handle SSL, see issue #29.

I suppose that option has also been deprecated, so now we have to freeze React to a version that plays nice, until someone has enough time to actually resolve the issue 😅 

I just pushed a change on branch `develop-interpreter` (that's the branch I'm using for development) which should help.

Please try pulling, doing `git switch develop-interpreter`, and trying again!

**Comment by aaniculaesei** [comment]
Hi Luca, 

Thanks for your response. I pulled the changes from the `develop-interpreter` branch. Unfortunately, it did not work. I also tried the command `npm install --legacy-peer-deps`.

The error in the command line from the npm command is:
```
npm ERR! code 9
npm ERR! path /home/adina/rcheck/frontend-react/node_modules/core-js
npm ERR! command failed
npm ERR! command sh -c node -e "try{require('./postinstall')}catch(e){}"
npm ERR! node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
```
Notice that, irrespective of whether I run `npm install` or `npm install --legacy-peer-deps`, the error `npm ERR! node: --openssl-legacy-provider is not allowed in NODE_OPTIONS` appears in both cases.

Even though the command `npm` did not work, I changed to the parent directory, `rcheck/`, and ran`mvn clean` and `mvn install`. Some errors appear during the tests. Attached is the corresponding `.log` file, [mvn-install.log](https://github.com/user-attachments/files/17375748/mvn-install.log). 

Are these issues connected to each other or are they separate issues?

**Comment by lou1306** [comment]
They appear to be separate issues.

## npm

I've made a few other changes to `package.json`. Can you please try `npm install` again? If that fails, can you please also paste here the outputs of `npm --version` and `node --version`?

## mvn

There was a lot of cruft on this side of things :) first, we now use Java 18 rather than 15, the `README.md` was out of date (apologies, I've updated it). On my machine I was also able to compile (`mvn clean package`) with Java 23, but 18 is the oldest suppoerted version.

Also, one of the dependency repositories we were using was shut down; I've updated the `pom.xml` accordingly. I don't know if that is enough, though, as I was not able to reporduce your specific test failure (yet).

**Comment by aaniculaesei** [comment]
Hi Luca, 

Thanks for the quick fix. This time it seems that `npm install` doesn't report any errors, i.e., it just says it's up to date, audited 2055 packages and found 166 vulnerabilities.

However, when running `mvn clean` and `mvn install` in the `/rcheck` directory, I get some errors and the `.jar` file is not built. It seems that the error appears in the assertion `recipe.lang.expressions.predicate.IsEqualToTest`. Attached is the complete debug log.
[mvn-install-errors.log](https://github.com/user-attachments/files/17391810/mvn-install-errors.log)

**Comment by lou1306** [comment]
> Thanks for the quick fix. This time it seems that npm install doesn't report any errors, i.e., it just says it's up to date, audited 2055 packages and found 166 vulnerabilities.

Yeah, at some point we should analyze the npm output and start updating our dependencies. There was a plan to put an R-CHECK demo online sooner or later, but definitely not in this state :)

> However, when running mvn clean and mvn install in the /rcheck directory, I get some errors and the .jar file is not built. It seems that the error appears in the assertion recipe.lang.expressions.predicate.IsEqualToTest. Attached is the complete debug log.

Yes, that's another weird thing. When I run `mvn` everything works on my side. For context, we store enumerated types in a  static hashmap in the Enum class. For those tests, we need to initialize the test system so it contains a `channels` enumeration. But somehow, on your machine such an enum already exists.

At any rate, since this is test code after all, I just worked around it by clearing all enums before adding `channels`. Can you try and see if it works now?

**Comment by aaniculaesei** [comment]
Hi Luca,

Yes, I can compile and build the `.jar` file. When I execute the `.jar` file, the Firefox browser in my Ubuntu VM does not open and the execution holds right after the start.
```
> frontend-react@0.1.0 start
> react-scripts --max_old_space_size=4096  --openssl-legacy-provider start
WARN: No handler found for: GET /favicon.ico
```
I've opened both ports 3000 and 54044 on the VM and this is shown by the output of the command `sudo ufw status verbose`:
```
To                         Action      From
--                         ------      ----
80,443/tcp (Apache Full)   ALLOW IN    Anywhere                  
3000                       DENY IN     Anywhere                  
54044                      DENY IN     Anywhere                  
3000                       ALLOW IN    127.0.0.1                 
54044                      ALLOW IN    127.0.0.1                 
80,443/tcp (Apache Full (v6)) ALLOW IN    Anywhere (v6)             
3000 (v6)                  DENY IN     Anywhere (v6)             
54044 (v6)                 DENY IN     Anywhere (v6) 
```
However, the running of the `.jar` file starts a process which listens on the port 54044. This is shown by the output of the command `sudo netstat -tulpn | grep LISTEN`:

```
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      706/cupsd           
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      392/systemd-resolve 
tcp6       0      0 :::80                   :::*                    LISTEN      13719/apache2       
tcp6       0      0 :::54044                :::*                    LISTEN      25445/java          
tcp6       0      0 ::1:631                 :::*                    LISTEN      706/cupsd  
```

If I open by hand `localhost:54044` in the browser, I get a simple page on which it simply says `Started`. As is to be expected, calling `localhost:3000` yields the error message `Unable to connect`.

I also installed with the help of Yehia R-CHECK under Windows from the `main` branch. Interestingly enough, when I run the `.jar` file in a terminal, it opens the `localhost:3000` in the default browser showing the R-CHECK model checker as expected.

**Comment by lou1306** [comment]
Ok, we're making progress!

A few notes on what you're seeing. Essentially R-CHECK starts a lightweight server on port 3000 that hosts the frontend Web app. This app, in turn, sends requests to *another* server, which listens to port 54044, and offers an HTTP API (plus the `Started` message you saw. It means the server is running).

The message about the favicon is rather strange. In any case, when you try and visit the GUI on port 3000, are you doing that from within your VM of from your host OS? That may change things. I also just realised that `localhost` is hardcoded in some requests, which might break things sometimes.

Also, notice that earlier today I pushed some changes to `package.json` to update some of our dependencies and reduces the number of vulnerabilities. Please check that you're running the latest version of the code.

Again, I'm not sure you sent me that already, but what versions of `npm` and `node` are you running?

**Comment by aaniculaesei** [comment]
Hi Luca,

I pulled out your changes, the number of vulnerabilities was drastically reduced from over 150 to 12. My current `npm` version is `8.5.1`, my current `node` version is `v12.22.9`. I saw during `npm install` that it was complaining about the `node` version and that it should be higher than 14. I'll probably need to update that.

I am trying to access the GUI on port 3000 from inside the VM not from the Windows host. At the moment, running the `.jar` file still does not open the GUI in the browser inside the VM.

As a point of interest, I was able to install R-CHECK on my computer at home. On this computer, I have a dual boot system, with Ubuntu and Windows installed in parallel. I was able to compile, build and execute R-CHECK with `Java 23`, `Maven 3.8.8`, `npm 10.9.0` and `node v23.0.0`. I opened the ports 3000 and 54044 on `ufw`, and running the `.jar` file with the `-g` option opens the GUI in the browser.

Another thing I noticed is that if I have the `nuxmv` binaries included in the `$PATH` environment variable, I don't have to copy the full `nuxmv` installation directory in the `rcheck` root directory. Of course I still need to rename `nuXmv` to `nuxmv` and so on.

**Comment by lou1306** [comment]
For reference, here's what I am running on my laptop:

```bash
❯ npm --version
10.8.3
❯ node --version
v22.9.0
```

Given that you were able to run R-CHECK on both Windows and your home computer, I suspect this is an issue with an old Node version. Please try updating node and let me know if you still have issues.

> Another thing I noticed is that if I have the nuxmv binaries included in the $PATH environment variable, I don't have to copy the full nuxmv installation directory in the rcheck root directory. Of course I still need to rename nuXmv to nuxmv and so on.

Yes, this makes sense. The logic that looks for nuxmv (in `Config.getNuxmvPath()`) will just assume that it is in the `$PATH` if it cannot find it in the other locations. We should maybe change the `README.md` to reflect that.

**Comment by aaniculaesei** [comment]
I updated `node` and `npm` as shown below:
```
> node -v
v23.0.0

> npm -v
10.9.0
```

Running the `.jar` file starts the GUI on `localhost:3000` automatically, as it is supposed to.

Many thanks for your help. I think this issue can be closed.

**Comment by lou1306** [comment]
Glad we figured it out, and that we improved a couple things along the way. Will mark this as closed.
