### ISSUE TITLE
Reserved local variable names

### ISSUE THREAD

**Issue by frans-bergman** [dSynMa/recipe#4]
The local variable name `state` is reserved by the `ToNuXmv` code generator, where it is used to represent the current agent state. If one uses declares a local variable named `state`, this causes a conflict error during model checking. This error is not clearly reported to the user, but can be found by running the `nuxmv` manually.

Is it possible to use a different name for the internal state representation or, alternatively, clearly report that `state` is a reserved word that cannot be used as a variable name?

**Comment by shaunazzopardi** [comment]
Good point! I'll change the nuxmv model to use a different variable name for the automaton states (maybe aut-state), since 'state' is probably a natural variable name one may want to use in the RCHECK script.

**Comment by shaunazzopardi** [comment]
A different name for the internal state is now being used (automaton-state), from commit e566cc81c4798ef809489d89f23b2272d4f12149.
