### ISSUE TITLE
Uniformization of the enum types syntax in R-CHECK models

### ISSUE THREAD

**Issue by aaniculaesei** [dSynMa/recipe#40]
There is an inconsistency between the definition of the type `channels` and the definition of the types `rolevals` and `msgvals` in the **Autonomous Resource Allocation** example.

The type `channels` is defined as:
`channels: c, empty, g1, g2,vmm1,vmm2,vmm3,t`

The types `rolevals` and `msgvals` are defined:
`enum rolevals {clnt, vm, mgr}`
and
`enum msgvals {reserve, request, release, buy, connect, full,complete}`. 

However, the understanding is that all three types are enumeration types. Thus, the syntax should be uniform for all such types. An example of how the unified syntax for enumeration types could look like is:

```
channels: c, empty, g1, g2,vmm1,vmm2,vmm3,t
rolevals: clnt, vm, mgr
msgvals: reserve, request, release, buy, connect, full,complete
```

**Comment by lou1306** [comment]
Given that we're decommissioning the `recipe` parser in favor of the `rcheck` one I will mark this as "not planned" and we can move the discussion to https://github.com/dSynMa/rcheck/issues/10.
