### ISSUE TITLE
Overlapping identifiers cause parsing failure

### ISSUE THREAD

**Issue by frans-bergman** [dSynMa/recipe#5]
Using variable names or enum variants where one identifier contains the other as a prefix causes parsing to fail.

For example:

This works
```
guard g0(p1 : bool, p2: bool) := (p1 && p2);
```
but this does not work
```
guard g0(p : bool, p2: bool) := (p && p2);

```

**Comment by shaunazzopardi** [comment]
This has been repaired with commit bd83d73.
